version: 2.1

orbs:
  node: circleci/node@4.7
  sonarcloud: sonarsource/sonarcloud@1.0.2

commands:
  npm_install:
    description: 'Install & Cache Dependencies'
    steps:
      - run: npm install -f
      - save_cache:
          key: ht-company-{{ checksum "package-lock.json" }}
          paths:
            - ~/.cache
            - node_modules

  restore_npm_cache:
    description: 'Restore Cached Dependencies'
    steps:
      - restore_cache:
          keys:
            - htcompany-{{ checksum "package-lock.json" }}
            - htcompany- # used if checksum fails

  setup:
    description: 'Setup Executor'
    steps:
      - checkout
      - attach_workspace:
          at: ~/project

jobs:
  initialise:
    executor:
      name: node/default
    steps:
      - checkout
      - restore_npm_cache
      - npm_install
      - persist_to_workspace:
          root: ~/project
          paths:
            - node_modules
            - dist

  build-spring:
    docker:
      - image: 'circleci/openjdk:11-jdk'
    steps:
      - checkout
      - run:
          name: Build Spring project
          command: |
            cd ./apps/nx-spring-example
            chmod +x ./gradlew
            ./gradlew build

  build:
    executor:
      name: node/default
    steps:
      - setup
      - run:
          name: Build all affected projects
          command: npx nx affected:build --base=master --head=HEAD

  test:
    executor:
      name: node/default
    steps:
      - setup
      - run:
          name: Build all affected projects
          command: npx nx affected:test --base=master --head=HEAD
    parallelism: 2

  scan:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - sonarcloud/scan

workflows:
  build-and-test:
    jobs:
      - initialise
      - build-spring:
          requires:
            - initialise
      - build:
          requires:
            - initialise
      - test:
          requires:
            - initialise
            - build-spring
            - build
      - scan:
          context: SonarCloud
          requires:
            - initialise
            - build-spring
            - build
