# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@4.7
  sonarcloud: sonarsource/sonarcloud@1.0.2

commands:
  npm_install:
    description: 'Install & Cache Dependencies'
    steps:
      - run: npm install -f
      - save_cache:
          key: ht-company-{{ checksum "package-lock.json" }}
          paths:
            - ~/.cache
            - node_modules

  restore_npm_cache:
    description: 'Restore Cached Dependencies'
    steps:
      - restore_cache:
          keys:
            - htcompany-{{ checksum "package-lock.json" }}
            - htcompany- # used if checksum fails

  setup:
    description: 'Setup Executor'
    steps:
      - checkout
      - attach_workspace:
          at: ~/project

jobs:
  initialise:
    executor:
      name: node/default
    steps:
      - checkout
      - restore_npm_cache
      - npm_install
      - persist_to_workspace:
          root: ~/project
          paths:
            - node_modules
            - dist

  test:
    executor:
      name: node/default
    steps:
      - setup
      - run:
          name: Build all affected projects
          command: npx nx affected:test --base=master --head=HEAD

  scan:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - sonarcloud/scan

workflows:
  build-and-test:
    jobs:
      - initialise
      - test:
          requires:
            - initialise
          parallelism: 4
      - scan:
          requires:
            - initialise
